version: '2'
services:
  web:
    env_file:
      - .env
    build: .
    command: npm run pm
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgres://${DB_USER}@postgres/${DB_NAME}'
  postgres:
    env_file:
      - .env
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
